class AppString {
  static List planets = [
    {
      'name': 'Earth',
      'file': 'images/Earth_1_12756.glb',
      'img': 'assets/img_earth.png',
      'year' : '365 Earth Day',
      'type' :'Terrestrial',
      'radius' : "339.6 KM",
      'des':'Earth—our home planet—is the only place we know of so far that’s inhabited by living things. It is also the only planet in our solar system with liquid water on the surface',
    },
    {
      'name': 'Mercury',
      'file': 'images/Mercury_1_4878.glb',
      'img': 'assets/mercury.png',
      'year' : '88 Earth Day',
      'type' :'Terrestrial',
      'radius' : "2439.4 KM",
      'des':'Mercury—the smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth iss Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.',
    },
    {
      'name': 'Venus',
      'file': 'images/Venus(surface)_1_12103.glb',
      'img': 'assets/img_venus.png',
      'year' : '225 Earth Days',
      'type' :'Terrestrial',
      'radius' : "6051.8 KM",
      'des':'Venus spins slowly in the opposite direction from most planets. A thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.',
    },
    {
      'name': 'Mars',
      'file': 'images/Mars_1_6792.glb',
      'img': 'assets/img_mars.png',
      'year' : '687 Earth Day',
      'type' :'Terrestrial',
      'radius' : "3396.2 KM",
      'des':'Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence Mars was—billions of years ago—wetter and warmer, with a thicker atmosphere.',
    },
    {
      'name': 'Jupiter',
      'file': 'images/Jupiter_1_142984.glb',
      'img': 'assets/jupiter.png',
      'year' : '4333 Earth Day',
      'type' :'Terrestrial',
      'radius' : "71492.0 KM",
      'des': 'Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet is Great Red spot is a centuries-old storm bigger than Earth.',
    }, {
      'name': 'Saturn',
      'file': 'images/Saturn_1_120536.glb',
      'img': 'assets/sature.png',
      'year' : '10,759 Earth Day',
      'type' :'Gas Glant',
      'radius' : "60268.0 KM",
      'des': 'Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn is.',
    }, {
      'name': 'Neptune',
      'file': 'images/Neptune_1_49528.glb',
      'img': 'assets/Neptune.png',
      'year' : '60,990 Earth Day',
      'type' :'Gas Glant',
      'radius' : "26764.0 KM",
      'des': 'Neptune—the eighth and most distant major planet orbiting our Sun—is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations, rather than by telescope.',
    },
  ];
}